export { createTalentOfficer, createTalentSettings, modifyTalentOfficer } from './ontology/actions.js';
export * as $Actions from './ontology/actions.js';
export {} from './ontology/interfaces.js';
export * as $Interfaces from './ontology/interfaces.js';
export { TalentOfficer, TalentSettings } from './ontology/objects.js';
export * as $Objects from './ontology/objects.js';
export {} from './ontology/queries.js';
export * as $Queries from './ontology/queries.js';
export { $osdkMetadata } from './OntologyMetadata.js';
export { $branch, $ontologyRid } from './OntologyMetadata.js';
